name: NexusTags
version: '1.0'
main: org.fahri.nexusone.NexusTags
api-version: '1.21'
author: JektDIVI
commands:
  tag:
    description: Main command for NexusTags
    permission: nexustags.use
permissions:
  nexustags.use:
    default: true
  nexustags.admin:
    default: op